# Generated by Django 5.2.4 on 2025-07-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_room_numero_alter_guest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='numero',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
