# Generated by Django 5.2.4 on 2025-07-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_room_id_alter_room_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='reservation.guest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='reservation.room'),
            preserve_default=False,
        ),
    ]
