# Generated by Django 5.2.4 on 2025-07-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_guest_alter_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
