# Generated by Django 5.2.4 on 2025-07-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_guest_correo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set(),
        ),
    ]
