# Generated by Django 5.2.4 on 2025-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_guest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='telefono',
            field=models.CharField(blank=True),
        ),
    ]
